apiVersion: 1

datasources:
  - name: PostgreSQL
    uid: postgres
    type: grafana-postgresql-datasource
    access: proxy
    url: postgres-sink:5432
    user: poc
    secureJsonData:
      password: poc123
    jsonData:
      database: salesdb
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
    isDefault: false
    editable: false
